version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gradeval_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gradeval360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gradeval_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gradeval.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # This line tells pgAdmin to import the servers
      PGADMIN_CONFIG_SERVER_MODE: 'False' 
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: